language: cpp
compiler:
  - clang
  - gcc
script: "./.travis/build"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-system-dev libboost-thread-dev libtinyxml-dev
matrix:
  allow_failures:
    - compiler: clang
