#!/usr/bin/env python

import roslib; roslib.load_manifest('urdf_parser_py')
import rospy

import sys

from urdf_parser_py.urdf import URDF

robot = None

def usage():
    print("display_urdf <urdf file>")
    print("\tLoad an URDF file.")
    print("display_urdf")
    print("\tDisplay the parameter server current robot description.")
    sys.exit(1)

if len(sys.argv) > 2:
    usage()
if len(sys.argv) == 2 and (sys.argv[1] == "-h" or sys.argv[1] == "--help"):
    usage()

if (len(sys.argv) == 1):
    robot = URDF.load_from_parameter_server()
else:
    robot = URDF.load_xml_file(sys.argv[1])

print(robot)

if robot:
    print(robot.to_xml())
