# Find version components
STRING (REGEX REPLACE "^([0-9]+).*" "\\1" URDF_MAJOR_VERSION "${URDF_VERSION}")
STRING (REGEX REPLACE "^[0-9]+\\.([0-9]+).*" "\\1" URDF_MINOR_VERSION "${URDF_VERSION}")
STRING (REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+)" "\\1" URDF_REVISION_VERSION ${URDF_VERSION})
STRING (REGEX REPLACE "^[0-9]+\\.[0-9]+\\.[0-9]+(.*)" "\\1" URDF_CANDIDATE_VERSION ${URDF_VERSION})
