---
name: urdfdom ROS1 CI

on:
  push:
  pull_request:

jobs:
  build_ros1:
    name: ROS1 CI
    runs-on: ubuntu-18.04
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: melodic
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: urdfdom
          target-ros1-distro: melodic
